# Generated by Django 4.1.5 on 2023-01-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='clicks',
            field=models.IntegerField(verbose_name='Количество кликов'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='views',
            field=models.IntegerField(verbose_name='Количество просмотров'),
        ),
    ]
