# Generated by Django 4.1.5 on 2023-01-06 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statistics', '0002_alter_statistics_clicks_alter_statistics_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatisticsRalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'normal'), (4, 'good'), (5, 'nice')])),
                ('like', models.BooleanField(default=False)),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.statistics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
