# Generated by Django 4.1.5 on 2023-01-06 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statistics', '0003_userstatisticsralation'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='readers',
            field=models.ManyToManyField(through='statistics.UserStatisticsRalation', to=settings.AUTH_USER_MODEL),
        ),
    ]
