# Generated by Django 4.1.5 on 2023-01-06 17:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statistics', '0004_statistics_readers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStatisticsRalation',
            new_name='UserStatisticsRelation',
        ),
    ]
