# Generated by Django 4.1.5 on 2023-01-06 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statistics', '0005_rename_userstatisticsralation_userstatisticsrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_statistics', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistics',
            name='readers',
            field=models.ManyToManyField(related_name='statistics', through='statistics.UserStatisticsRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
