# Generated by Django 4.1.5 on 2023-01-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0006_statistics_owner_alter_statistics_readers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatisticsrelation',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'normal'), (4, 'good'), (5, 'nice')], null=True),
        ),
    ]
